language: java

env:
    - SCALA_VERSION=2.11.7

os:
    - osx

script: ./sbt "++$SCALA_VERSION" compile jacoco:cover

matrix:
  include:
    - env: SCALA_VERSION=2.11.7
      os:  linux
      jdk: oraclejdk8

before_install:
    - curl -s https://raw.githubusercontent.com/paulp/sbt-extras/master/sbt > sbt && chmod 0755 sbt
    - pip install --user codecov

after_success:
    - codecov

addons:
    s3_region: "us-east-1"
    artifacts:
        debug: true
        paths:
            - $(git ls-files -o | grep libzstd | tr "\n" ":")
