version: '{build}'
os: Windows Server 2012
environment:
  matrix:
    - MSYSTEM: MINGW64
      JAVA_HOME: "C:\Progra~1\Java\jdk1.8.0"
    - MSYSTEM: MINGW32
      JAVA_HOME: "C:\Progra~2\Java\jdk1.8.0"
install:
  - echo: Starting install of SBT
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\sbt" )) {
        (new-object System.Net.WebClient).DownloadFile(
          "https://dl.bintray.com/sbt/native-packages/sbt/0.13.9/sbt-0.13.9.zip",
          "C:\sbt-bin.zip"
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\sbt-bin.zip", "C:\sbt")
      }
  - cmd: SET PATH=C:\msys64\usr\bin;C:\sbt\sbt\bin;%JAVA_HOME%\bin;%PATH%
build_script:
  - sbt clean compile
test_script:
    sbt test
cache:
  - C:\sbt\
  - C:\Users\appveyor\.ivy2
