version: '{build}'
os: Windows Server 2012
environment:
  matrix:
    - MSYSTEM: MINGW64
      MSYS_PATH: C:\msys64\mingw64\usr\bin;C:\msys64\mingw64\bin
      JAVA_HOME: C:\Progra~1\Java\jdk1.8.0
      ARCH: amd64
    - MSYSTEM: MINGW32
      MSYS_PATH: C:\msys64\mingw32\usr\bin;C:\msys64\mingw32\bin
      JAVA_HOME: C:\Progra~2\Java\jdk1.8.0
      ARCH: x86
install:
  - echo: Starting install of SBT
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\sbt" )) {
        (new-object System.Net.WebClient).DownloadFile(
          "https://dl.bintray.com/sbt/native-packages/sbt/0.13.9/sbt-0.13.9.zip",
          "C:\sbt-bin.zip"
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\sbt-bin.zip", "C:\sbt")
      }
  - cmd: SET PATH=%MSYS_PATH%;C:\sbt\sbt\bin;%JAVA_HOME%\bin;%PATH%
build_script:
  - sbt clean compile
test_script:
    sbt test
artifacts:
  - path: target\classes\win
    name: $("windll_"+$env:ARCH)
deploy:
  provider: S3
  region: us-east-1
  access_key_id:
    secure: ACQ24Wiqzklv2JpYXATc8CYSDFpBDSObRA6K5rme4eI=
  secret_access_key:
    secure: d8vzb7gfYxlpZuyLzdDQzrvDt6WVoi9H6RPJKwCX8aLxMwYGDW55szksQ9MxFxCi
  bucket: zstd-jni
  set_public: false
  folder: appveyor
  artifact: $("windll_"+$env:ARCH)

cache:
  - C:\sbt\
  - C:\Users\appveyor\.ivy2
