name: CI nix amd64
on: [push, pull_request]
jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest]
        runs-on: ${{ matrix.os }}
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
            java-version: 8
        - name: Compile
          run: ./sbt compile
        - name: Test
          run: ./sbt jacoco
