  name: CI
  on: [push, pull_request]
  jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
          fail-fast: false
      steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
      - name: Compile
        run: sbt compile
      - name: Test
        run: sbt test
